# Generated by Django 4.0.10 on 2024-06-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cars',
            new_name='car',
        ),
    ]
