# Generated by Django 4.0.10 on 2024-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0003_avrage_car_economy_car_luxury_car_special_deals_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='avrage_car',
        ),
        migrations.AddField(
            model_name='economy_car',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='luxury_car',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='special_deals_car',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
