# Generated by Django 4.0.10 on 2024-06-25 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c7_motors', '0004_premium_car_delete_avrage_car_economy_car_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, default='nothing', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
