# Generated by Django 4.0.10 on 2024-09-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0010_carrental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
