# Generated by Django 4.0.10 on 2024-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0011_delete_carrental_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_data',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customers_data',
            name='date',
        ),
        migrations.AddField(
            model_name='customers_data',
            name='price',
            field=models.TextField(blank=True, default=''),
        ),
    ]
