# Generated by Django 4.0.10 on 2024-09-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0012_delete_carrental_remove_customers_data_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_data',
            name='drop_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='drop_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='pick_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
