# Generated by Django 4.0.10 on 2024-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0013_delete_carrental_customers_data_drop_off_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
