# Generated by Django 4.0.10 on 2024-09-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0015_delete_carrental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_car',
            old_name='insurnce',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='economy_car',
            old_name='insurnce',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='luxury_car',
            old_name='insurnce',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='premium_car',
            old_name='insurnce',
            new_name='insurance',
        ),
    ]
