# Generated by Django 4.0.10 on 2024-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0016_rename_insurnce_all_car_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers_data',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='economy_car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='luxury_car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premium_car',
            name='price',
            field=models.IntegerField(),
        ),
    ]
