# Generated by Django 4.0.10 on 2024-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0020_alter_customers_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_data',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
