# Generated by Django 4.0.10 on 2024-09-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0021_alter_customers_data_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_data',
            name='price',
        ),
    ]
