# Generated by Django 4.0.10 on 2024-09-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0024_customers_data_completed_alter_customers_data_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_data',
            name='completed',
        ),
        migrations.AlterField(
            model_name='customers_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
