# Generated by Django 4.0.10 on 2024-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0025_remove_customers_data_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_car',
            name='insurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='economy_car',
            name='insurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='luxury_car',
            name='insurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premium_car',
            name='insurance',
            field=models.IntegerField(),
        ),
    ]
