# Generated by Django 4.0.10 on 2024-10-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0027_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pre_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_bookings', to='c7_motors.premium_car')),
            ],
        ),
        migrations.CreateModel(
            name='Luxury_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('lux_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_bookings', to='c7_motors.luxury_car')),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('cate_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_bookings', to='c7_motors.all_car')),
            ],
        ),
    ]
