# Generated by Django 4.0.10 on 2024-10-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0028_premium_booking_luxury_booking_categories_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_data',
            name='drop_off_location',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='pick_up_location',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
