# Generated by Django 4.0.10 on 2024-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='avrage_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='economy_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='luxury_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='special_deals_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='car',
        ),
    ]
