# Generated by Django 4.0.10 on 2024-06-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0005_report_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='economy_car',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='luxury_car',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='premium_car',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='special_deals_car',
            name='cost',
        ),
        migrations.AddField(
            model_name='economy_car',
            name='insurnce',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='economy_car',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='luxury_car',
            name='insurnce',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='luxury_car',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='premium_car',
            name='insurnce',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='premium_car',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='special_deals_car',
            name='insurnce',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='special_deals_car',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
