# Generated by Django 4.0.10 on 2024-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_motors', '0008_all_car_cart_categories_reservation_customers_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_data',
            name='amount',
            field=models.TextField(blank=True, default=''),
        ),
    ]
